workflows:
  ios-workflow:
    name: iOS Workflow
    publishing:
      app_store_connect:
        auth: integration 
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Testers
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: lt.pro3D.kosmosas
      vars:
        APP_ID: 6448805235
      flutter: stable
      xcode: '13.4.1'
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: 'lt.pro3D.kosmosas'
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Set buikd number
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release --verbose \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log