name: Kosmosas
description: App about Lithuanian space science.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.7+14
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.9.3+2
  location: ^4.4.0
  easy_localization: ^3.0.1
  panorama: ^0.4.1
  flutter_image_slideshow: ^0.1.4
  assets_audio_player: ^3.0.6
  flutter_unity_widget: ^2022.2.0
  latlong2: ^0.8.1
  url_launcher: ^6.1.10
  geolocator: ^9.0.2
  geocoding: ^2.1.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/panoramas/
    - assets/images/gallery/
    - assets/images/icons/
    - assets/images/targets/
    - assets/images/instructions/
    - assets/audio/

  fonts:
    - family: Sans Serif
      fonts:
        - asset: assets/fonts/ebrima.ttf
        - asset: assets/fonts/ebrimabd.ttf
          weight: 600
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
